name: darkspace-backend

services:
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    # env_file:
    #   - ./../.env
    container_name: db-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/data/postgres
    networks:
      - dksp

networks:
  dksp:
    driver: bridge

volumes:
  db-data:


  # api:
  #   build:
  #     context: .
  #     dockerfile: api.Dockerfile
  #   ports:
  #     - 6789:6789
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_USER=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #   env_file:
  #     - ../.env
  #   depends_on:
  #     - database
  #   networks:
  #     - dksp
